backend:
  name: github
  repo: eddyv/personal-website

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Author", name: "author", widget: "string", default: "Edward Vaisman" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "date_published", widget: "date" }
      - { label: "Featured Image", name: "og_image", widget: "image" }
      - { label: "Featured Image Description", name: "og_image_description", widget: "string"}
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
